resources:
  - name: gitrepo_res_jTest
    type: gitRepo
    repoPath: kirtisahu05/newTest
    configuration:
      integrationName: git_kirti
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res_jTest
    type: file
    fileLocation: https://raw.githubusercontent.com/kirtisahu05/jfrogTest/master/test.yml
    fileName: shippable.yml
    configuration:
      integrationName: git_kirti
    initialVersion:
      fileDtTm: random_value

  - name: image_res_jTest
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: docker_kirti
    initialVersion:
      imageTag: latest

  - name: stateResource_jTest
    type: state

  - name: webhookRes_jTest
    type: webhook
    configuration:
      integrationName: docker_kirti
    initialVersion:
      payload: "asd"

  - name: clusterRes_jTest
    type: cluster
    configuration:
      integrationName: docker_kirti
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration

pipelines:
  - name: jTest_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step_jTest
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
          resources:
            - image_res_jTest
            - stateResource_jTest
        triggeredBy:
          resources:
            - gitrepo_res_jTest
            - image_res_jTest
            - webhookRes_jTest
            - clusterRes_jTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res_jTest
          - stateResource_jTest
